### ISSUE TITLE
Support display:table*

### ISSUE THREAD

**Issue by ComLock** [tristen/tablesort#102]
Currently tablesort only works on real table elements, not tables created using display:table*

For example:
Making a table row that is a link, and works "cross-browser/-os" with middle-click, control/cmd-click to open in background tab/window, and so on, is quite difficult and requires a bunch of js.

The much easier alternative is making a "fake" table there the table row is actually an anchor with display: table-row.

Would be nice if that could be sortable to.

**Comment by tristen** [comment]
Other contributors can re-open this if they disagree but tablesort is pretty heavily burrowed in supporting table elements. There's no plans for supporting custom elements. Perhaps [list.js](http://listjs.com/) might suit your needs!
