### ISSUE TITLE
Sorting with multiple header rows

### ISSUE THREAD

**Issue by tarpack** [tristen/tablesort#105]
I have a table with two rows of headers. Basically something like this:

```
<table id="sortme">
    <thead>
        <th colspan="3"></th>
        <th>
            Past Sales
        </th>
    </thead>
    <thead>
        <th>
            Product
        </th>
        <th>
            Category
        </th>
        <th>
            Price
        </th>
        <th>
            Quantity
        </th>
        <th>
            Value
        </th>
    </thead>
    <tbody>
        ...
    </tbody>
</table>

<script src='tablesort.min.js'></script>
<script src='tablesort.number.js'></script>

<script>
  new Tablesort(document.getElementById('sortme'));
</script>
```

Building the headers like this keeps thing a bit more compact and visually appealing than having a single row of headers where the last two are something like "Past Sales (Quantity)" and "Past Sales (Value)". I want tablesort to use the second set of headers to sort by (clicking on anything in the first `thead` should not do anything). Is there a way to accomplish this? I'm happy to assign an id to the second `thead` element and then pass that in when I'm initializing the JS.

**Comment by JoshAddington** [comment]
@tarpack try setting second `thead` element to `<thead class='sort-row'>`

**Comment by tristen** [comment]
Documented here: http://tristen.ca/tablesort/demo/#specify-which-table-heading-row-enables-sorting
