### ISSUE TITLE
Mixed column has 4 sorts

### ISSUE THREAD

**Issue by richcaputo** [tristen/tablesort#107]
I have a column with values like this: $123.32, $20.00, N/A, -$123.23.

It has 4 different sorts. 1 that sorts them in descending with N/A at bottom, one is ascending with N/A at top, 1 I'm not sure of that mixes numbers, N/A and they are in no order, another with the same method but in reverse. 

How can I get this to just sort ascending and descending without the 2 random orders in the mix?

**Comment by tristen** [comment]
@richcaputo I know this is a dreadfully late response but there's a few options here:

- [You can override the data that's sorted on](http://tristen.ca/tablesort/demo/#override-data-that-is-sorted-on). So a `N/A` could be represented as `data-sort='0'`
- If you want the `N/A` row to just remain in place you can [exclude the row from being sorted](http://tristen.ca/tablesort/demo/#exclude-columns-or-rows)
- You can override [tablesort.number.js](https://github.com/tristen/tablesort/blob/gh-pages/src/sorts/tablesort.number.js) by providing your own using [extend](https://github.com/tristen/tablesort#extending-tablesort) that accounts for values like `N/A`

Hope that helps!
