### ISSUE TITLE
Use aria-sort

### ISSUE THREAD

**Issue by chaals** [tristen/tablesort#108]
The sorted column should provide an `aria-sort` attribute. The obvious thing is to actually use this as the key instead of the `sort-up` / `sort-down` class.

**Comment by davidjb** [comment]
+1 

Also, in the current implementation, `aria-sort` persists on column headings after the sort order has changed so it'd have to be cleared from the old sort column for this to work.

**Comment by chaals** [comment]
> `aria-sort` persists on column headings after the sort order has changed

That sounds like a simple stupid bug, of the sort I probably introduced and nobody picked up :( @tripu ?
