### ISSUE TITLE
configurable sort classes

### ISSUE THREAD

**Issue by hyperborea** [tristen/tablesort#110]
Would it be possible to make the sort classes (sort-up & sort-down) configurable through options? I'd like to use table sort together with semantic-ui and need to have different class names for that to work properly.

**Comment by stylemistake** [comment]
Same issue here, coming from Semantic UI too.

I hope this gets merged, so I can no longer use this:

```js
$('.ui.sortable.table');
  .each(function (i, element) {
    new Tablesort(element);
  });
  .on('afterSort', function () {
    var $headers = $(this).find('th');
    $headers.removeClass('sorted ascending descending');
    $headers.filter('.sort-down').addClass('sorted descending');
    $headers.filter('.sort-up').addClass('sorted ascending');
  });
```

**Comment by tristen** [comment]
After https://github.com/tristen/tablesort/pull/126 tablesort no longer relies on sort classes but data attributes instead!

**Comment by stylemistake** [comment]
@tristen this doesn't really fix our issue. :(

**Comment by xPaw** [comment]
@stylemistake I think using `afterSort` hook is a good way to fix this issue if you can't update your CSS.
