### ISSUE TITLE
Styling documentation isn't clear

### ISSUE THREAD

**Issue by davidjb** [tristen/tablesort#116]
In the docs about styling (http://tristen.ca/tablesort/demo/#style) it read as though the given CSS could be dropped into a page.  Looking at the source though, classes like `sort-header`, `sort-up` and `sort-down` aren't present anywhere so it appears as though a user of the library needs to always add their own code to add these classes in so the styles would then work.  Is this the case / intention?  

It's a bit confusing because issue #110 seems to imply the classes were present at some point.

**Comment by tristen** [comment]
Hey @davidjb those classes were recently removed from master via https://github.com/tristen/tablesort/pull/115. They haven't been bundled into a new release (but should be next week) The latest stable release should contain them though!

**Comment by davidjb** [comment]
Awesome, thanks @tristen.  Figured it was in a state of flux so thanks for the clarification.

As a suggestion, might it be worth having the gh-pages site link to the latest stable version too?  Perhaps two buttons side-by-side, one for stable and one for development/master.  A one-liner about how the docs refer to the current stable version would help as well.

**Comment by tristen** [comment]
@davidjb ooof good call. Will do.
