### ISSUE TITLE
un-duplicating the documentation

### ISSUE THREAD

**Issue by tristen** [tristen/tablesort#119]
It was a mistake to duplicate usage documentation in the README.md and here: http://tristen.ca/tablesort/demo/. It just leads to copy errors. There should be one place to avoid unnecessary duplication.

- Having it on a demo page is nice to visualize each option. There's also way more control how it's presented.
- Having it in the README.md is nice as npm pulls it in and there's less clicks to reach it. But there's no reason why we can't add a big link that says __Demo / Docs__ or some such. 

cc @xPaw for thoughts.

**Comment by xPaw** [comment]
Having it in a single place is indeed better. If you were to update the demo page with extra documentation then that's fine by me.

**Comment by tripu** [comment]
@tristen, perhaps there's a way to have here a `README.md` that is almost empty (only pointing to demo/docs) and still tell `npmjs.com` to look for documentation somewhere else?

I found [`stackoverflow.com/a/30326985/45758`](http://stackoverflow.com/a/30326985/45758), but doesn't look very reliable, and I can't find it documented on `npmjs.com`.
