### ISSUE TITLE
Descending not working properly

### ISSUE THREAD

**Issue by JelmerD** [tristen/tablesort#12]
The descending doesn't seem to work properly.

I am building my < tbody > via an Ajax call. When the Ajax calls the success callback function, I call the the sort.refresh();. Ascending works fine, but when sorting descending the values scatter around. And not in the default order, but in some random order.

# edit
I found the pattern it is sorting by. For instance I have a few integers in the second column. When I sort "sort-up" it will create the following newRows order.

232, 221, 24, 22, 21, 193, 153, 152, 12, 1.

So, it is sorting by the first number of the integer first, then it is looking at the second number. For some reason it works fine when ordering in the "sort-down" configuration. So the newRows.reverse() function (line 172) seems to fix this bug. I have no clue why. You might want to have a look at it?

Have a look at http://i50.tinypic.com/2mzbhpy.jpg

# edit
Also, I seem to fix the problem when I order another column first. So for example I have the column "total" and "deleted", I can sort the "total" with "sort-up" when first sorting the "deleted" column. It's getting stranger and stranger :)

**Comment by xPaw** [comment]
Using `data-sort` fixes this issue.
