### ISSUE TITLE
Drop manipulations with classnames entirely?

### ISSUE THREAD

**Issue by xPaw** [tristen/tablesort#124]
Most of the sorting happens in attributes now, and we can move remaining `no-sort`, `sort-row` and `sort-default` to be data attributes. Thoughts?

**Comment by 9uuso** [comment]
Makes sense for consistency.

**Comment by tripu** [comment]
I'm in favour in principle. But, aren't classes better for styling (more natural, CSS rules are simpler, etc)&hellip;?

**Comment by tristen** [comment]
@xPaw did this in https://github.com/tristen/tablesort/pull/126 🎉
