### ISSUE TITLE
Aria-Sort attribute values are reversed

### ISSUE THREAD

**Issue by johnpgreen** [tristen/tablesort#128]
When a columnheader is clicked to initiate a sort, the value of the aria-sort attribute is the opposite of the type of sort currently applied.

Steps to produce:

1) Visit http://tristen.ca/tablesort/demo/
2) Click the "Price" column header

Expected Result: values are sorted in ascending order, with $0.63 first and $12.09 last. Aria-sort value is "ascending"

Actual Result: values are sorted in ascending order, with $0.63 first and $12.09 last. Aria-sort value is **"descending"**

**Comment by tripu** [comment]
@tristen, perhaps I messed that up in #115 or #117&hellip; :worried:

**Comment by webgefrickel** [comment]
I can confirm the reversed logic. The aria-attributes should describe the state, not the 'this is what will happen' when I click on the header again :)

**Comment by tristen** [comment]
If you want to test that hunch ^ I would heartily love a pull request.

**Comment by tripu** [comment]
@tristen, I think #145 closed this one.
