### ISSUE TITLE
Enhancement: multilevel sorting

### ISSUE THREAD

**Issue by JelmerD** [tristen/tablesort#13]
I am having a table which has recursive data. What that means is that the table has some sort of grouping labels in certain rows.

For example my table could look like this:
(Just for good measure, my table is a Pivot Table which uses "Brand" as the first label and "Category" as the second label.

Brand | Quantity in stock
* G-star | 20
  * Pants | 10
  * Shirts | 7
  * Shoes | 3
* Vans | 7
  * Shirts | 6
  * Shoes | 1

That is the result I would like when sorting on "Quantity in Stock"

When I sort on Brand I would like to have it ordered by Brand, but the name of the brand (in my case) should act as a "parent" of the items in it.

What a solution might be:

Adding some sort of a "Level" integer to the data-level attribute of a < tr >. Maybe this won't work that great, so perhaps a data-parent attribute where you can add the id of the parent. Which is a integer as well. I don't want to use the id attribute for this, since I don't want to use that in this case. I just want to assign an integer if that is possible.

:+1:  I am working for my company on a system that really needs this plugin. You have made only plugin that works properly (besides of #12 but that doesn't matter). We need your plugin, so I am hoping you are willing to put some extra time in the code. I am not that great in Js, so I can't do it myself. I'm more of a PHP guy :)

**Comment by xPaw** [comment]
Sorry for late response, but would using `data-sort` attribute fix this issue? If not, a custom sorting method could be created after #75 is merged.

**Comment by xPaw** [comment]
This most likely can be solved by creating a custom sort in v3.0.0, so I will close this issue.
