### ISSUE TITLE
arrow still shown when data-sort-method='none'

### ISSUE THREAD

**Issue by pheyvaer** [tristen/tablesort#137]
I think https://github.com/tristen/tablesort/blob/gh-pages/src/tablesort.js#L113 should move inside the if that follows. That solves the problem in my case.

**Comment by tripu** [comment]
Have you tried adding the `no-sort` class to the column (`<th>`)?
That prevents the arrow from showing when hovering over, and also fixes the cursor (no pointer).

```html
<table id="tests" class="sort">
  <thead>
    <tr>
      <th>foo</th>
      <th data-sort-method="none" class="no-sort">bar</th>
      <th>baz</th>
    </tr>
  </thead>
  <tbody> ⋯ </tbody>
</table>
```

**Comment by savisky** [comment]
Have you tried adding the no-sort class to the column (<th>)?
I tried its working. Thanks!
