### ISSUE TITLE
sorting error

### ISSUE THREAD

**Issue by ctf0** [tristen/tablesort#148]
sorting columns with 

- dashes ex.`north-toreyburgh`
- empty 
- @ ex.`hbuckridge@example.org`

gives error 
```
Cannot read property 'getAttribute' of undefined
```

**Comment by tripu** [comment]
@ctf0, I can't reproduce these bugs; I think you must be doing something wrong&hellip;

See [`https://codepen.io/tripu/pen/mpReLr`](https://codepen.io/tripu/pen/mpReLr).

**Comment by ctf0** [comment]
i re-checked and u r right, the table wasn't correctly formatted, thanx for the examples 👍
