### ISSUE TITLE
Sort on checkbox?

### ISSUE THREAD

**Issue by wgins** [tristen/tablesort#164]
Apologies if this has been discussed elsewhere. I did my best to search through closed issues!

I've got checkbox's within `td` that I'd like to sort on. Can anyone point me in the right direction on how I might go about extending tablesort to check if an input is checked? Thanks!

**Comment by tristen** [comment]
You might want to use a `data-sort` attribute with a value like `true` for checked and `false` for not. See http://tristen.ca/tablesort/demo/#override-data-that-is-sorted-on as example.
