### ISSUE TITLE
Unable to laod tablesort.number

### ISSUE THREAD

**Issue by florianajir** [tristen/tablesort#165]
I'm getting `Uncaught ReferenceError: Tablesort is not defined` when I'm loading the tablesort.number.js script.

**Comment by wgins** [comment]
Have you also imported `tablesort.js`? You'll need to include both files as `tablesort.number.js` extends `tablesort.js`.

**Comment by florianajir** [comment]
I was trying to use it in webpack, loading standalone tablesort is working but when I require tablesort.number it's throwing this Error. Anyway I switch to tablesorter.js and it's working properly, thanks for your help

**Comment by follesoe** [comment]
Same issue, the readme file only describes how to import the tablesort library, but not the additional sorts when using it in a npm/webpack context: `var tablesort = require('tablesort');`.

**Comment by m-grzybek-first10** [comment]
Any progress with that guys?

**Comment by cirosantilli** [comment]
Here's a reproducer: https://github.com/cirosantilli/cirodown/blob/f6d4e00fa159a37f2e45c1a4de72ee1726f72ac4/web2/pages/_app.tsx#L9
