### ISSUE TITLE
two tables on same page?

### ISSUE THREAD

**Issue by steo-dol** [tristen/tablesort#166]
I have two tables that need the sorting feature... I am not sure how to change the JavaScripts... Can anyone kindly help me?  Thanks.

<script>
  new Tablesort(document.getElementById('sort'));
</script>

**Comment by tristen** [comment]
Hey @steo-dol you do that by instantiating a new Tablesort object!

```html
<table id="first"></table>
<table id="second"></table>

<script>
new Tablesort(document.getElementById('first')); 
new Tablesort(document.getElementById('second')); 
</script>
```

Hope this helps!

**Comment by steo-dol** [comment]
Wow!  Thanks so much! They work. I really appreciate your helps.
