### ISSUE TITLE
Select multiple tables at once with class

### ISSUE THREAD

**Issue by AndiLeni** [tristen/tablesort#167]
Hello,

I wanted to know, wether it is possible to select multiple tables at onece, for example with the `getElementsByClassName` function instead of using `new Tablesort(document.getElementById('sort-2019'));` for each table.

Regards
Andi

**Comment by tristen** [comment]
Are you looking to sort multiple tables when a user clicks on the column heading of one table? You would need to manage this yourself by binding some click handler.

```js
table.addEventListener('afterSort', () => {
  // Emit the click event of another table's column.
});
```
If you are just looking to instantiate a collection of tables using `getElementsByClassName` you could do something like this:

```js
Array.prototype.forEach.call(document.getElementsByClassName('table-class'), el => {
  new Tablesort(el);
});
```
