### ISSUE TITLE
Sort by td attribute

### ISSUE THREAD

**Issue by Macro-Jackson** [tristen/tablesort#168]
Is there any way to sort by a td attribute instead of the td contents? 
Reason why I ask is because not always you want to present the value itself but sometime a different representation of the data. Example: review rating in stars.

**Comment by tristen** [comment]
@Macro-Jackson yep! by using a `data-sort` attribute. See the section under, ["Override data that is sorted on"](http://tristen.ca/tablesort/demo/#override-data-that-is-sorted-on).

**Comment by Macro-Jackson** [comment]
Super awesome!!! You rock!
