### ISSUE TITLE
Descending sort brings headers to bottom of table

### ISSUE THREAD

**Issue by P0werC0rd0fJustice** [tristen/tablesort#170]
When sorting by descending, the headers of the table are sent to the bottom of the table.

![image](https://user-images.githubusercontent.com/6677562/47828043-a7171080-dd57-11e8-8c7f-9eebc30f9a5f.png)
 - This screenshot is sorting by Priority

It will also put the headers in the middle of the table where the sorted column goes from negative to positive numbers.

![image](https://user-images.githubusercontent.com/6677562/47828090-e180ad80-dd57-11e8-8121-a3a4c217abab.png) 
- This screenshot is sorting by Completion %.

**Comment by tristen** [comment]
👋 my suspicion is the markup for your table isn't correct. Is your heading wrapped in a `<thead>` element?
