### ISSUE TITLE
How to run the demo

### ISSUE THREAD

**Issue by JacobWay** [tristen/tablesort#171]
I don't know how to run the demo example. Can some give some suggestions?

Under the directory of demo, there is a file of index.md, which can't be run under a server, like live-server of node.js.

**Comment by tristen** [comment]
Hey @JacobWay these day's it's not ideal but the site runs on [Jekyll](https://jekyllrb.com/). You'll need to install that to get started if you want to run the site locally. Otherwise, it's viewable here: http://tristen.ca/tablesort/demo/

Hope that helps!
