### ISSUE TITLE
2 tables on the page. Mobile version does not work

### ISSUE THREAD

**Issue by savisky** [tristen/tablesort#193]
I have two tables on the page. One is for the mobile version and it's hidden from the desktop version. 
1) Does Tablesort work for mobile?
2) If yes how to add that second table and make it work? 

Thanks

**Comment by tripu** [comment]
Off the top of my head, I don't think Tablesort would behave necessarily differently on a mobile browser than on desktop.

Are you sure the problems you found are not related to that second table being hidden? Have you tried reproducing the error on desktop&nbsp;&mdash;&nbsp;ie, having that second hidden table _also_ on desktop and checking if it behaves differently or not?

In principle, you could have any number of tables, like so:

```html
<table id="first"> ⋯ </table>
<table id="second"> ⋯ </table>
<table id="third"> ⋯ </table>
```

```js
new Tablesort(document.getElementById('first'));
new Tablesort(document.getElementById('second'));
new Tablesort(document.getElementById('third'));
```

Finally, please provide a working example (paste sources, or share on [Codepen](https://codepen.io/) or similar site).

**Comment by savisky** [comment]
Thanks, mate I already did and everything works like a charm. 
So you can see the live version here:
https://www.perfumetr.com/perfume/1-million/

Thanks
