### ISSUE TITLE
Demo code with colspan > 1 not representative

### ISSUE THREAD

**Issue by thoron** [tristen/tablesort#236]
The demo code in:

https://github.com/tristen/tablesort/blob/c2e470780d3f140d24442f8569db67b76618556f/demo/index.md?plain=1#L234

Differs from the actual rendered table code:

https://github.com/tristen/tablesort/blob/c2e470780d3f140d24442f8569db67b76618556f/demo/index.md?plain=1#L261

The diff being that columns with headers with `colspan != 1` all row must also share the same `data-sort-column-key="price"` attribute. The demo code should be updated to reflect this.

**Comment by tripu** [comment]
@thoron: I fixed that on [my own fork](https://github.com/tripu/tablesort); see it [rendered](https://tripu.github.io/tablesort/demo/).

It's not exactly as you say: `data-sort-column-key` is not required, even when there's a `colspan`. It'll be set by tablesort itself, but that doesn't mean it should appear on the initial markup.

Does it look right now?

**Comment by thoron** [comment]
@tripu using the https://tripu.github.io/tablesort/demo/ rendered example the sorting does not work:
![tablesort](https://user-images.githubusercontent.com/1374642/236199435-49cfd12c-66fc-4d1b-adaf-25c5a2d89208.gif)
Adding `data-sort-column-key` to the `td` elements the example works again. Can you still sort without the `data-sort-column-key` on the elements? If so could it be a browser issue, I am using Firefox 112.0.2 (64-bit)

**Comment by tripu** [comment]
@thoron: you are right! I would swear I saw it sorting OK after my changes. But no.

It should be OK now. Care to take another look, please?

**Comment by thoron** [comment]
@tripu Works for me :+1:

**Comment by thoron** [comment]
Thanks for the fix and for a nice piece of software :)
