### ISSUE TITLE
Sort on initial Tablesort creation?

### ISSUE THREAD

**Issue by jcwren** [tristen/tablesort#36]
The table is initially unsorted when it's loaded. Is there a mechanism (or a cute tricky way) to force sorting on an arbitrary column in the 'new Tablesort (...)' call?

I have a list of IP addresses that are built on the fly, but are unordered. When I call 'new Tablesort (...)', I'd like to be able to pass in a default column to sort on.

**Comment by tobias47n9e** [comment]
In case you found this by searching: The new version does not use a class but `<th ... data-sort-default>`.
