### ISSUE TITLE
Tests.

### ISSUE THREAD

**Issue by tristen** [tristen/tablesort#44]
Definitely need to write some and [tape](https://www.npmjs.org/package/tape) is great.

**Comment by ryanmjacobs** [comment]
Hey @tristen, how would you feel about converting from tape.js to is.js? Their [homepage](http://arasatasaygin.github.io/is.js/) looks pretty convincing...

**Comment by tristen** [comment]
@ryanmjacobs Its not clear to me what moving over to is.js gives us. tape.js is well maintained and while its lacking in some method chaining features that is.js provides I don't really know that we need them? Maybe in the futrue?

**Comment by ryanmjacobs** [comment]
Your right, why fix something that isn't broke? I guess there isn't any real reason to move to is.js other than it has a clean interface.

**Comment by xPaw** [comment]
I've looked at tests, and there definitely should be more of them.

For example in version sorting: `3.1`, `3.1.0`, `3.0.1`, `3.1.0.1`, etc. Otherwise it's not clearly visible if sorting actually works as expected.

**Comment by tristen** [comment]
Oh yes there should be more tests but this ticket was getting pretty stale. Let's cut individual ones out for specific scenarios.
