### ISSUE TITLE
override sort algorithm for specific column

### ISSUE THREAD

**Issue by furier** [tristen/tablesort#53]
Ability to override sort algorithm for a specific column or for whole table.

**Comment by timbowhite** [comment]
Hi, I had the same need (my use case was making sure empty table cells were always sorted last).  I updated to the tablesort lib to allow a custom function to be passed per column.  Demo here (try sorting the "Price" column):

http://jsfiddle.net/v1ftnoce/

Code and docs here: https://github.com/timbowhite/tablesort

tablesort guys: let me know if you'd like this as a pull request.
