### ISSUE TITLE
sort-default direction is backwards

### ISSUE THREAD

**Issue by timbowhite** [tristen/tablesort#62]
Specifying the defaut sort dir (via the "descending" option on object instantiation) and giving a `<th>` the "sort-default" class results in the opposite sort direction.

[http://jsfiddle.net/4auneqkk/1/](http://jsfiddle.net/4auneqkk/1/)

**Comment by timbowhite** [comment]
Should be fixed by #63

**Comment by xPaw** [comment]
It looks like default option is backwards regardless of specifying `descending` or not.
