### ISSUE TITLE
Using data-sort with numbers with decimals reverses intended sort order

### ISSUE THREAD

**Issue by timbowhite** [tristen/tablesort#64]
For instance, giving `<td>`'s a `data-sort="0.79"` sorts the opposite direction (but sort still seems correct).

http://jsfiddle.net/5uxesa5q/

**Comment by timbowhite** [comment]
Looks like numbers with decimals are being sorted as "dot separted numbers".  See commits above for simple fix.

**Comment by ryanmjacobs** [comment]
Hey @timbowhite, I've fixed that issue. The '<' and '>' signs were swapped. That's all it was.

http://jsfiddle.net/qhq7cwdL/
