### ISSUE TITLE
Callback after a table is sorted

### ISSUE THREAD

**Issue by xPaw** [tristen/tablesort#66]
Either a callback that can be provided in options, or an event that is triggered for the table element.

I have a lazy load for images, and I want to trigger a check after user sorts the table.

**Comment by tristen** [comment]
Yeah, this is a good thing to have.

**Comment by xPaw** [comment]
I've added a `callback` option, need to document that.

**Comment by xPaw** [comment]
Perhaps a pre-sort callback would be good as well, and how about triggering events on `table` element instead of callbacks?

**Comment by tristen** [comment]
:+1: triggering events + pre-sort event

**Comment by xPaw** [comment]
Okay I did that. It might be a good idea to make pre-sort event cancellable, but I'm not entirely sure how to that.

I`ll leave it up to you to document it.

**Comment by tristen** [comment]
@xPaw :+1: will document. I'd also like to simplify these event names to `sortstart` and `sortend`. I think we're safe here not to prefix.

**Comment by xPaw** [comment]
I think presort would be a better name.

**Comment by xPaw** [comment]
How about `beforeSort` and `afterSort`?

**Comment by tristen** [comment]
:+1:

**Comment by tristen** [comment]
Done in https://github.com/tristen/tablesort/commit/ad91994658baede8b2cfc637fb003e4dc104c745
