### ISSUE TITLE
Sort gets stuck in one direction.

### ISSUE THREAD

**Issue by tonglil** [tristen/tablesort#67]
I am using backbone to load a collection into a table.

After it loads, THEN I create and call the sort. However, it gets stuck sorting the table in the initial direction, and refuses to sort in the other direction.

If anyone has had experience or tips with this, your information would be highly appreciated.

**Comment by tristen** [comment]
@tonglil Can you set up a [jsfiddle](jsfiddle.net) that demonstrates this? You mention you are initializing the sort after the content has been loaded to the page -- so this might not help -- but, have you tried using [refresh](https://github.com/tristen/tablesort#refresh-sort-on-appended-data)?

**Comment by xPaw** [comment]
@tonglil Try again with v3.0.0.

**Comment by tristen** [comment]
Closing. @tonglil feel free to re-open if the issue persists!
