### ISSUE TITLE
TypeError: that.getInnerText is not a function

### ISSUE THREAD

**Issue by xxluke** [tristen/tablesort#68]
I get the javascript error "TypeError: that.getInnerText is not a function" in tablesort.js:330 (or "TypeError: b.getInnerText is not a function" in the minified version) when I have a cell with a <span> for an icon in it.

btw. support for dates in format dd.mm.yyyy would be nice.

**Comment by ryanmjacobs** [comment]
Hi, what does the cell look like? Is it something like this: `<td><img src="..."></td>`?

**Comment by xxluke** [comment]
No, it uses `<span>`:
`<td><span class="glyphicon glyphicon-remove" title="No"></span></td>`

**Comment by ryanmjacobs** [comment]
@xxluke I just pushed a commit that should fix it.

**Comment by xPaw** [comment]
I don't think that's a good fix. Any other element could be empty too.

**Comment by ryanmjacobs** [comment]
Yeah, that is true. Maybe we could use a try...catch statement instead?

**Comment by xPaw** [comment]
How about we don't do anything recursive at all, and just tell developers to use `data-sort` on <td> elements if they want to sort it?

**Comment by ryanmjacobs** [comment]
I think that it's better to handle these cases since the issue has now popped up twice (#24 and #68). But I guess we'll need @tristen's input before we move on.

**Comment by tristen** [comment]
Yeah, like @xPaw I'd recommend `data-sort` and not come up with any solution cases like this. In instances like this enabling a [custom sort for a specific column](https://github.com/tristen/tablesort/issues/53) option in the future might be a good solution.

We should probably handle the error better and prevent the TypeError though.

**Comment by xPaw** [comment]
Won't removing nodeType == 1 from switch fix the problem?

**Comment by tristen** [comment]
Yep. Just needs to get done.

**Comment by xPaw** [comment]
@tristen If you're fine with the code I provided above, I can commit that.

**Comment by tristen** [comment]
@xPaw :+1: in a pull request would be good so Travis can run.

@ryanmjacobs thinking we should revert this: https://github.com/tristen/tablesort/commit/bb1c8dd5de8a650b9b599aef7b5f283fc2d6953e ?

**Comment by xPaw** [comment]
Won't travis run on repository pushes? And there's no need to revert that if we're going to replace it completely.

**Comment by tristen** [comment]
> Won't travis run on repository pushes?

It runs on pushes yes. I'd like to see tests pass in a branch before it's merged into `gh-pages`

**Comment by ryanmjacobs** [comment]
Yeah, I guess it's better to keep it simple. Sorry, for jumping the gun. :pensive:

#70 looks good to me, (and simplifies a lot). Just curious, will there ever be a case (other than undefined or null) where the element doesn't have a `.getAttribute` or `.textContent` causing to give a TypeError?

Also, maybe we should check for null as well so we don't try to access it?
```js
if (typeof el === 'string' || el == null) return el;
```
(btw, `el == null` [covers both undefined and null](http://stackoverflow.com/a/15992131))

**Comment by xPaw** [comment]
#70 fixed this.
