### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by xPaw** [tristen/tablesort#72]
This happens in filesize2num, however I am unsure which value causes that to happen.

Happens on this page: https://steamdb.info/app/211420/depots/

**Comment by ryanmjacobs** [comment]
@xPaw Hmm, what line does it occur on with the unminified script?

**Comment by xPaw** [comment]
https://github.com/tristen/tablesort/blob/gh-pages/src/tablesort.js#L323 this one

**Comment by xPaw** [comment]
I've found which value causes that to explode. `filesize2num( '100.00 MB (104857600)' )`

**Comment by ryanmjacobs** [comment]
Yeah, that's weird. It doesn't pass the `testFilesize` and yet it still uses `sortFilesize`.

I've made a quick fix, not requiring a newline right after the filesize works alright. This allows you to have things like: `100.34 MB sdfasdfs this whole thing is garbage but it still passes`.

**Comment by xPaw** [comment]
I'm not sure that's a good fix.

**Comment by ryanmjacobs** [comment]
Yes, we should probably figure out *why* it fails the test regex but is still passed onto the sort function. 

Should we also not require a newline, or is that unrelated?

**Comment by xPaw** [comment]
Well I found the problem. That regex matches for simple numbers too. Try `filesize2num( '1337' );
