### ISSUE TITLE
Extending tablesort

### ISSUE THREAD

**Issue by xPaw** [tristen/tablesort#74]
Discussion started here: https://github.com/tristen/tablesort/commit/9a8b294e504e74d71546a59902467d99fe2c0049#commitcomment-9804379

Basically, move algorithms like dot separated sorting and file size sorting into separate plugins, and allow extending tablesort. We can do that by either having a new method to register new sorting methods, or provide them in options argument.

**Comment by xPaw** [comment]
@tristen How do you think this should work?

**Comment by 9uuso** [comment]
Just my two cents, but I personally support modularization. People who fork the code to add their own functionality could PR the changes to plugins, which might save work hours from other people whilst keeping the original codebase clean.

**Comment by ryanmjacobs** [comment]
We could have an individual file for each additional sort in a folder called `src/sorts/`. Then use grunt to concat and minify all of the sources into `tablesort.min.js`. Each sort would provide its global `testSort` and `actualSort`, (all the helper functions for that sort would be private). Then, in the main loop, where we [check for different sorts](https://github.com/tristen/tablesort/blob/gh-pages/src/tablesort.js#L92) we can call these sorts in order.

I think something like that would work well.

**Comment by xPaw** [comment]
That sounds fine, however sort methods like dot-sep and filesizes should be disabled by default, and they should be pluggable without being concat into output file.

**Comment by tristen** [comment]
Just spitballing but I see this as a public method called `extend` that takes two parameters: 

1. The regex pattern to capture it
2. The sort function itself

``` javascript
Tablesort.extend(pattern, function(a, b) {
	// Return the sort between a + b
});
```
Unless this needs to be more robust? And yeah, putting these in a file structure like `src/sorts/numbers.js` And only concatenating core ones like numbers and strings.

**Comment by tristen** [comment]
Done in https://github.com/tristen/tablesort/commit/ad91994658baede8b2cfc637fb003e4dc104c745
