### ISSUE TITLE
Data-sort Not Taking Precedence

### ISSUE THREAD

**Issue by torpeyp** [tristen/tablesort#76]
I am trying to sort two columns with irregular data. As per the documents, I gave each a data-sort attribute to take precedence over the actual information. 

Each time I try to use them however, I am given an error saying that the variable is undefined:

tablesort.min.js:5 Uncaught TypeError: Cannot read property 'match' of undefined

![sort](https://cloud.githubusercontent.com/assets/8345483/6318807/6e11b81e-ba72-11e4-80bb-baeaf4d8d78c.jpg)

**Comment by torpeyp** [comment]
![sort](https://cloud.githubusercontent.com/assets/8345483/6318827/eb8ce4da-ba72-11e4-8690-0970df6c1047.jpg)

**Comment by xPaw** [comment]
Could you make a jsfiddle.net with some test data?

**Comment by torpeyp** [comment]
http://jsfiddle.net/m36gdx8y/

**Comment by torpeyp** [comment]
I am only trying to sort the last two columns. Earlier, I was able to sort the first column, so I know it is initializing, but i still believe it is looking only at the information in the cell

**Comment by xPaw** [comment]
Weird, it's working for me.

**Comment by torpeyp** [comment]
I'm still not able to sort them on my end. Could it be a browser issue?

**Comment by xPaw** [comment]
You didn't include jQuery in your jsfiddle, that's why it didn't work, http://jsfiddle.net/m36gdx8y/2/

**Comment by torpeyp** [comment]
That's strange. I'm using JQuery on my app. 

Well, thank you for the help. I should be able to sort this out. I think it may have to do with a row I have spanning the bottom.

**Comment by xPaw** [comment]
I think that JS error might be related to filesize sort method, which I've run into before. You should try again after #74/#75 are fixed.

**Comment by torpeyp** [comment]
It was entirely in issue with having a row that spanned more than one column. I used a no-sort class and was fine. Thank you, I wouldn't have noticed that without your help.

**Comment by xPaw** [comment]
Ah yeah, that is indeed an issue (#48)
