### ISSUE TITLE
Calling tablesort() with generator (instead of instantiating new object) throws error

### ISSUE THREAD

**Issue by ilikescience** [tristen/tablesort#82]
The `init` function doesn't exist when tablesort is used via npm, despite the docs saying otherwise.

this works:
```
var Tablesort = require('tablesort');
var thisTable = new Tablesort(el);
```

this doesn't:
```
var tablesort = require('tablesort');
tablesort(el)
```

**Comment by xPaw** [comment]
Oops, I put wrong issue number in my last commit, didn't mean to close this issue.

**Comment by tristen** [comment]
Whoops! looks like this needs the ol' `instanceOf` tricky trick trick

```js
if (!(this instanceof Tablesort)) return new Tabelsort(el, options);
```

**Comment by iris-cloud** [comment]
Can somebody please provide an explanation what is 'el' and 'options' in this context and maybe add an example how it works. I'm new to this stuff, sorry
