### ISSUE TITLE
Sort a date column that has empty cells

### ISSUE THREAD

**Issue by orrsiloni** [tristen/tablesort#83]
When sorting a date column that has some empty cells (or for that matter any cell that doesn't contain a valid date) it screws up the sort since parseDate returns `NaN`.
I applied a fix locally, don't have the energy now to push a fix so I'm posting it here.

tablesort.date.js : parseDate
 change this line:
`return new Date(date).getTime();`

to this:
`return new Date(date).getTime() || 0;`

**Comment by xPaw** [comment]
Fixed in 180fcda61b9a77b16ea2d34936a58f08a9e1dd50
