### ISSUE TITLE
Text wrap on verbose columns lost after sort.

### ISSUE THREAD

**Issue by bentwonk** [tristen/tablesort#84]
Hi
Love the functionality of tablesort, but I have an issue with it sorting columns that require wordwrap,

When when a sort is applied to the initial result (beforeSort.png) the table re-formats so that each row is one line high, (afterSort.png) which has the effect of shoving half the table outside the viewing area.

I tried altering the table css, (table-layout: fixed; word-wrap: break-word;) etc, but now the text overwrites itself (withTableLayoutFixed.png)

Is it possible to sort, while preserving multi-line text in a column?

Cheers Ben

![aftersort](https://cloud.githubusercontent.com/assets/1641837/6888368/d2b7b3d4-d6c6-11e4-89f9-c6b74e324272.png)
![beforesort](https://cloud.githubusercontent.com/assets/1641837/6888369/d3da47d6-d6c6-11e4-99ae-8b45e82ec471.png)
![withtablelayoutfixed](https://cloud.githubusercontent.com/assets/1641837/6888371/d6f40d80-d6c6-11e4-923a-cfcc50b44218.png)

**Comment by 9uuso** [comment]
Mind pasting some of the code used in your table to jsfiddle or codepen? It would make debugging possible for us.

**Comment by bentwonk** [comment]
Here is my little test case. I suspect its more to do with my css.

Also can linked text be embedded into the table? and be invisible to the
search?

Thank you

Ben

**Comment by 9uuso** [comment]
@bentwonk are you sure you pasted any code? I can see none...

**Comment by bentwonk** [comment]
ahh I sent you a zip, you have an email I can send it too?

**Comment by 9uuso** [comment]
I'd really appreciate if you could paste your code to either [jsfiddle](https://jsfiddle.net/) or [codepen](http://codepen.io/).

**Comment by bentwonk** [comment]
UI put my code up at
http://jsfiddle.net/#&togetherjs=7buL68vjsG

but I don't use jfiddle, so don't know how to include the tablesort.js file

**Comment by 9uuso** [comment]
Ugh, just re-send the zip file to my email address shown on my Github profile. The jsfiddle you sent me does not work.

**Comment by tristen** [comment]
@bentwonk Can you simplify your test case and not use togetherjs? Just the html table with content and an initialization of Tablesort. This will make it easier to debug/fix.

You can add an external script in JSFiddle by selecting __External Resources__ from the left sidebar.

**Comment by bentwonk** [comment]
Here you go

thanks
Ben

**Comment by tristen** [comment]
Closing. Feel free to re-open @bentwonk if you can simplify your test case as [outlined above](https://github.com/tristen/tablesort/issues/84#issuecomment-88884717)
