### ISSUE TITLE
Sorting on numbers with decimals are not working properly

### ISSUE THREAD

**Issue by ahmedelgabri** [tristen/tablesort#85]
Here is a very reduced test case for this http://jsbin.com/gedubukaye/1/

**Comment by xPaw** [comment]
You need to include `tablesort.numeric.js`

**Comment by ahmedelgabri** [comment]
@xPaw and how to do that with CommonJS?

**Comment by ahmedelgabri** [comment]
So I did this _not the cleanest way, but it works_ I copied the file inside my directory and exported the modified Tablesort instance.
```js
"use strict";

var Tablesort = require('tablesort');

var cleanNumber = function(i) {
    return i.replace(/[^\-?0-9.]/g, '');
},

compareNumber = function(a, b) {
    a = parseFloat(a);
    b = parseFloat(b);

    a = isNaN(a) ? 0 : a;
    b = isNaN(b) ? 0 : b;

    return a - b;
};

Tablesort.extend('number', function(item) {
    return item.match(/^-?[£\x24Û¢´€]?\d+\s*([,\.]\d{0,2})/) || // Prefixed currency
        item.match(/^-?\d+\s*([,\.]\d{0,2})?[£\x24Û¢´€]/) || // Suffixed currency
        item.match(/^-?(\d)*-?([,\.]){0,1}-?(\d)+([E,e][\-+][\d]+)?%?$/); // Number
}, function(a, b) {
    a = cleanNumber(a);
    b = cleanNumber(b);

    return compareNumber(b, a);
});


module.exports = Tablesort;
```

and then `var Tablesort = require("./tablesort.numeric")`

I think maybe you should publish these as separate _plugins/extensions_ or export `Tablesort` with all the sort methods inside.

The 2nd option might work now cause the number of extensions are not that big yet but maybe later separate npm extensions will be a better idea.
