### ISSUE TITLE
Multi-column sorting‏ 

### ISSUE THREAD

**Issue by sauribea** [tristen/tablesort#86]
Hello.
Is it possible Multi-column sorting‏?
Example:
I have table with columns: ORDEN, NOMBRE, FECHA, HORA, STATUS
So, I need set multi-sort when the table is loaded like this:
First sort: STATUS
Second: FECHA
and the last sort: ORDEN
Is it possible?
Thank you very much.

**Comment by tristen** [comment]
@sauribea Not totally following. Can you model your example in HTML and Tablesort using [jsfiddle](jsfiddle.net) to describe the issue?

**Comment by sauribea** [comment]
Thank you very much for response it.

Well, is very simple. This is my html code:

            <table id="tblMonitor">
                <thead>
                    <tr>
                        <th class="mayu">Orden</th>
                        <th class="mayu">Paciente</th>
                        <th class="mayu">Estudio</th>
                        <th class="mayu">Fecha de Entrega</th>
                        <th class="mayu">Hora de Entrega</th>
                        <th class='sort-default'>Status</th>
                    </tr>
                </thead>
                <tbody>
................

So, I set the coumn "Status" must be default column sort, but I can't specify another columns to sort too. I need the first one column to default sort "Status" like example, but after that the second column I need sort to "Fecha de Entrega" and Finally "Orden"... then the question is: How can I set that type order for my table?, sort default: "Status", second: "Fecha de Entrega" and finally: "Orden"

Is it possible using tablesort framework?

Thank you very much.

Regards.


Sergio Alfonso Uribe Arias
Sistemas Computacionales
Cel: 5540820416



Date: Wed, 20 May 2015 05:12:10 -0700

**Comment by tristen** [comment]
I'm still not connecting the dots. 

Are you adding a [`sort-default`](https://github.com/tristen/tablesort#default-sort-on-tablesort-initialization) class name to "Status" so it's sorted when Tablesort is initialized and then expect another column to sort? What's the use case? Sorting happens in rapid succession and would largely be unnoticed by the user. Tablesort is designed for a user to interact with header to view a column sort. If you really require sorts to happen automatically and in a particular order I would suggest using a dom library like jQuery to select each header and fire a click handler.

**Comment by sauribea** [comment]
Ok.

I try with:
jQuery plugin: Tablesorter 2.0Supports multi-column sort, the problem with this plugin, is not sort correctly the column with numbers data.


But, thank you very much foy your help and cooperation.


Regards.


Sergio Alfonso Uribe Arias
Sistemas Computacionales
Cel: 5540820416



Date: Wed, 20 May 2015 21:52:28 -0700

**Comment by tristen** [comment]
:+1: Not sure we'll support multi column sorting as in [tablesorter](http://tablesorter.com/docs/).
