### ISSUE TITLE
Sort by Surname

### ISSUE THREAD

**Issue by coldes** [tristen/tablesort#87]
How to Sort by Surname in alpha order in a table column that contains for example:
```
Dr Fred Smith
Mr Joe Day
Mary Allen
```
so default load would be
```
    Mary Allen
    Mr Joe Day
    Dr Fred Smith
```
thank you

**Comment by 9uuso** [comment]
If you have a way to display the name without the title, you could use the `data-sort` helper, as such: https://jsfiddle.net/ns3zxd93/

If you don't have an easy way to display the names without the titles, I think you are going to need to play with JavaScript quite a lot.

**Comment by tristen** [comment]
Or just use the surname in the `data-sort` attribute?

**Comment by 9uuso** [comment]
> Or just use the surname in the data-sort attribute?

I think I lost my thought when making the example. But yeah @coldes, do it as @tristen said.

**Comment by coldes** [comment]
...thank you, yes by adding surname to data-sort has worked
```
<tr><td data-sort="Day">Mr Joe Day</td></tr>
<tr><td data-sort="Allen">Mary Allen</td></tr>
<tr><td data-sort="Smith">Dr Fred Smith</td></tr>
