### ISSUE TITLE
can't work on IE8

### ISSUE THREAD

**Issue by zhucong1986** [tristen/tablesort#90]
can't work on IE8

**Comment by shaneneuerburg** [comment]
Main issue seems to be with .classList not being supported. Until resolved, you can hack it by adding the following script:

https://raw.githubusercontent.com/eligrey/classList.js/master/classList.js

**Comment by xPaw** [comment]
Yeah, we wouldn't want to go back to dealing with `className`, including that shim should fix the issue.

Perhaps we can mention this in the readme?
