### ISSUE TITLE
Number or numeric?

### ISSUE THREAD

**Issue by Amorymeltzer** [tristen/tablesort#92]
Of the five provided [alternative sorts](https://github.com/tristen/tablesort/tree/gh-pages/src/sorts), `tablesort.numeric.js` is the only one whose filename (numeric) doesn't match the Tablesort.extend function (number).  This could be confusing!  I'd suggest picking one or the other; this'd be a PR but I figured you might have a preference as to which.

**Comment by xPaw** [comment]
Good point, fixed!

**Comment by Amorymeltzer** [comment]
:+1:
