### ISSUE TITLE
 Rename tablesort.numeric.js to tablesort.number.js is breaking change

### ISSUE THREAD

**Issue by iamstarkov** [tristen/tablesort#99]
as far as im using [bundle system](https://github.com/iamstarkov/jsunderhood/blob/master/js/index.js#L11-L12) to pick only needed tablesort plugins, I rely on filesystem, so 8268fca5c82e4e7105c3b25cf32f7640e573692a is definitely breaking change. Can we do something about it?

**Comment by xPaw** [comment]
3.2.0 would have to be removed and re-released as 4.0.0, unsure if this is a great idea.

**Comment by iamstarkov** [comment]
I also don't think it's good idea, but broken sites aren't good too though

**Comment by iamstarkov** [comment]
@tristen what do you think?

**Comment by tristen** [comment]
I think https://github.com/tristen/tablesort/issues/99#issuecomment-165092161 should happen along with a `npm depricate` message.

**Comment by iamstarkov** [comment]
will you do that?

**Comment by tristen** [comment]
Yep done.

**Comment by iamstarkov** [comment]
thank you
